
public class ExceptionHandlingDemo {

	// try
	// catch
	// finally
	// throw
	// throws
	
	public static void main(String[] args) {
		int a = 20;
		int b = 0;
		int c = 0;
		
		System.out.println("Going to divide:");
		
		try {
		c = a / b;
		} catch(ArithmeticException ae) {
			System.out.println(ae.getMessage());
			b = 1;
			c = a / b;
		}
		System.out.println("Division over");
		System.out.println("the answer is  : " + c);


	}

}
