
public class ExceptionHandlingDemo {

	// try
	// catch
	// finally
	// throw
	// throws
	
	public static void main(String[] args) {
		int a = 20;
		int b = 0;
		int c = 0;
		
		System.out.println("Going to divide:");
		
		try {
		c = a / b;
		// 1. in the above line JVM figures out an exception has occured
				// 2. the jvm identifies the type of exception that occured i.e ArithmeticException
				// 3. an object of ArithmeticException is created
				// 4. the exception object is thrown implicity
		} catch(ArithmeticException ae) {
			System.out.println(ae.getMessage());
			b = 1;
			c = a / b;
		}
		System.out.println("Division over");
		System.out.println("the answer is  : " + c);
	}
}
